Ext.define('contactlist.view.AddGroup',{
	extend:'Ext.form.Panel',
	xtype:'addgroup-form',
	controllers:['AddGroup'],
	config:{
		id:'addgroup-form',
		styleHtmlCls:true,
		fullscreen:true,
		items:[
		{
			xtype:'titlebar',
			docked:'top',
			title:'新增群组',
			items:[
			{
				text:'保存',
				align:'right',
				pressedCls:false,
				id:'saveGroup'
			},
			{
				text:'返回',
				align:'left',
				pressedCls:false,
				handler:function(){
					history.go(-1);
				}
			}
			]
		},
		{
			xtype:'fieldset',
			items:[
				{
					xtype:'textfield',
					id:'groupName',
					label:'群组名称',
					placeHolder:'请输入群组名称'
				}
			]
		},
		{
			id:'groupUser'
		},
		{
			text:'添加群组成员',
			id:'addGroupUser',
			xtype:'button'
		}
		]
	}
});