Ext.define('contactlist.view.Login',{
	extend:'Ext.Container',
	xtype:'login',
	id:'login',
	config:{
		fullscreen:true,
		items:[
			{
				xtype:'toolbar',
				title:'用户登录'
			},
			{
				xtype:'fieldset',
				items:[
				{
					xtype:'textfield',
					label:'用户名',
					name:'username',
					id:'username'
				},
				{
					xtype:'passwordfield',
					label:'password',
					name:'password',
					id:'password'
				}
				]
			},
			{
				xtype:'button',
				text:'登录',
				id:'loginbtn',
				pressedCls:false,
				style:{height:'30px'}
			},
			{xtype:'spacer',style:{height:'30px'}},
			{
				xtype:'button',
				text:'体验',
				id:'mainbtn',
				pressedCls:false,
				style:{height:'30px'}
			}
		]
	}
})